// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

module DecoupledGcd(	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7]
  input        clock,	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7]
  input        reset,	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7]
  output       input_ready,	// @[src/main/scala/myproject/DecoupledGCD.scala:24:18]
  input        input_valid,	// @[src/main/scala/myproject/DecoupledGCD.scala:24:18]
  input  [7:0] input_bits_value1,	// @[src/main/scala/myproject/DecoupledGCD.scala:24:18]
  input  [7:0] input_bits_value2,	// @[src/main/scala/myproject/DecoupledGCD.scala:24:18]
  input        output_ready,	// @[src/main/scala/myproject/DecoupledGCD.scala:25:18]
  output       output_valid,	// @[src/main/scala/myproject/DecoupledGCD.scala:25:18]
  output [7:0] output_bits_value1,	// @[src/main/scala/myproject/DecoupledGCD.scala:25:18]
  output [7:0] output_bits_value2,	// @[src/main/scala/myproject/DecoupledGCD.scala:25:18]
  output [7:0] output_bits_gcd	// @[src/main/scala/myproject/DecoupledGCD.scala:25:18]
);

  wire [63:0] _impl_out;	// @[src/main/scala/myproject/SimTime.scala:22:22]
  reg  [7:0]  xInitial;	// @[src/main/scala/myproject/DecoupledGCD.scala:27:24]
  reg  [7:0]  yInitial;	// @[src/main/scala/myproject/DecoupledGCD.scala:28:24]
  reg  [7:0]  x;	// @[src/main/scala/myproject/DecoupledGCD.scala:29:24]
  reg  [7:0]  y;	// @[src/main/scala/myproject/DecoupledGCD.scala:30:24]
  reg         busy;	// @[src/main/scala/myproject/DecoupledGCD.scala:31:28]
  reg         resultValid;	// @[src/main/scala/myproject/DecoupledGCD.scala:32:28]
  wire        _GEN = x == 8'h0;	// @[src/main/scala/myproject/DecoupledGCD.scala:29:24, :44:12]
  wire        _GEN_0 = _GEN | y == 8'h0;	// @[src/main/scala/myproject/DecoupledGCD.scala:30:24, :44:{12,20,25}]
  wire        _GEN_1 = busy & _GEN_0;	// @[src/main/scala/myproject/DecoupledGCD.scala:31:28, :44:{20,34}]
  `ifndef SYNTHESIS	// @[src/main/scala/myproject/DecoupledGCD.scala:54:13]
    always @(posedge clock) begin	// @[src/main/scala/myproject/DecoupledGCD.scala:54:13]
      if ((`PRINTF_COND_) & _GEN_1 & ~reset)	// @[src/main/scala/myproject/DecoupledGCD.scala:44:34, :54:13]
        $fwrite(32'h80000002, "time=%d resultvalid\n", _impl_out);	// @[src/main/scala/myproject/DecoupledGCD.scala:54:13, src/main/scala/myproject/SimTime.scala:22:22]
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire        _GEN_2 = output_ready & resultValid;	// @[src/main/scala/myproject/DecoupledGCD.scala:32:28, :56:25]
  always @(posedge clock) begin	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7]
    if (busy | ~input_valid) begin	// @[src/main/scala/myproject/DecoupledGCD.scala:27:24, :28:24, :31:28, :38:14, :63:23]
    end
    else begin	// @[src/main/scala/myproject/DecoupledGCD.scala:28:24, :38:14, :63:23]
      xInitial <= input_bits_value1;	// @[src/main/scala/myproject/DecoupledGCD.scala:27:24]
      yInitial <= input_bits_value2;	// @[src/main/scala/myproject/DecoupledGCD.scala:28:24]
    end
    if (busy) begin	// @[src/main/scala/myproject/DecoupledGCD.scala:31:28]
      if (x > y)	// @[src/main/scala/myproject/DecoupledGCD.scala:29:24, :30:24, :39:12]
        x <= x - y;	// @[src/main/scala/myproject/DecoupledGCD.scala:29:24, :30:24, :40:14]
      else	// @[src/main/scala/myproject/DecoupledGCD.scala:39:12]
        y <= y - x;	// @[src/main/scala/myproject/DecoupledGCD.scala:29:24, :30:24, :42:14]
    end
    else if (input_valid) begin	// @[src/main/scala/myproject/DecoupledGCD.scala:24:18]
      x <= input_bits_value1;	// @[src/main/scala/myproject/DecoupledGCD.scala:29:24]
      y <= input_bits_value2;	// @[src/main/scala/myproject/DecoupledGCD.scala:30:24]
    end
    if (reset) begin	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7]
      busy <= 1'h0;	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7, :31:28]
      resultValid <= 1'h0;	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7, :32:28]
    end
    else begin	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7]
      if (busy)	// @[src/main/scala/myproject/DecoupledGCD.scala:31:28]
        busy <= ~(_GEN_0 & _GEN_2) & busy;	// @[src/main/scala/myproject/DecoupledGCD.scala:31:28, :44:{20,34}, :56:{25,41}, :58:21]
      else	// @[src/main/scala/myproject/DecoupledGCD.scala:31:28]
        busy <= input_valid | busy;	// @[src/main/scala/myproject/DecoupledGCD.scala:31:28, :63:23, :69:16]
      if (_GEN_1)	// @[src/main/scala/myproject/DecoupledGCD.scala:44:34]
        resultValid <= ~_GEN_2;	// @[src/main/scala/myproject/DecoupledGCD.scala:31:28, :32:28, :53:26, :56:{25,41}, :59:21]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:1];	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7]
    initial begin	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7]
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7]
        end	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7]
        xInitial = _RANDOM[1'h0][7:0];	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7, :27:24]
        yInitial = _RANDOM[1'h0][15:8];	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7, :27:24, :28:24]
        x = _RANDOM[1'h0][23:16];	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7, :27:24, :29:24]
        y = _RANDOM[1'h0][31:24];	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7, :27:24, :30:24]
        busy = _RANDOM[1'h1][0];	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7, :31:28]
        resultValid = _RANDOM[1'h1][1];	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7, :31:28, :32:28]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  SimTimeImpl impl (	// @[src/main/scala/myproject/SimTime.scala:22:22]
    .clock (clock),
    .out   (_impl_out)
  );
  assign input_ready = ~busy & input_valid | ~busy;	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7, :31:28, :34:{16,19}, :38:14, :63:23]
  assign output_valid = resultValid;	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7, :32:28]
  assign output_bits_value1 = xInitial;	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7, :27:24]
  assign output_bits_value2 = yInitial;	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7, :28:24]
  assign output_bits_gcd = _GEN ? y : x;	// @[src/main/scala/myproject/DecoupledGCD.scala:23:7, :29:24, :30:24, :44:12, :45:23, :46:25, :48:25]
endmodule

